export { default as AuthenticationController } from '../../../auth/controllers/authentication.controller';
export { default as CalendarController } from '../../../business/v1/controllers/calendar.controller';
export { default as CaregiversController } from '../../../business/v1/controllers/caregivers.controller';
export { default as CollaboratorsController } from '../../../business/v1/controllers/collaborators.controller';
export { default as HealthUnitsController } from './health-units.controller';
// export { default as CustomersController } from './customers.controller';
export { default as FilesController } from '../../../files/controllers/files.controller';
export { default as OrdersController } from './orders.controller';
export { default as PatientsController } from './patients.controller';
export { default as PaymentsController } from './payments.controller';
export { default as ReviewsController } from './reviews.controller';
export { default as ServicesController } from './services.controller';
