version: "1.0.0"
name: backend
services:
  rest-api:
    stdin_open: true
    tty: true
    build: 
      context: ../../
      dockerfile: ./.docker/api/Dockerfile.stag
    image: careplace/rest-api:stag
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
    container_name: rest-api-stag
    environment:
      - APP_NAME=rest_api-staging
      - CHOKIDAR_USEPOLLING=true
    