# Set base image
FROM node:16.20.1-bookworm-slim

# Create app directory
WORKDIR /usr/src/app

# Copy host files to container
COPY . .

# Clean yarn cache
RUN yarn cache clean --force

# Install dependencies (--frozen-lockfile ensures yarn.lock is not modified)
RUN yarn install --frozen-lockfile

# Build the app
RUN yarn build

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["yarn", "start"]
