# Set base image
FROM node:20.8.1-bookworm-slim

# Create app directory
WORKDIR /usr/src/app

# Copy host files to container
COPY . .

# Clean yarn cache
RUN yarn cache clean --force

# Install dependencies using --production flag
RUN yarn install 

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["yarn", "dev"]
