# Set base image
FROM node:16.20.1-bookworm-slim

# Create app directory
WORKDIR /usr/src/app

# Install net-tools, curl, and gnupg
RUN apt-get update \
  && apt-get install -y --no-install-recommends net-tools curl gnupg lsof psmisc\
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Copy host files to container
COPY . .

# Set environment variables
ENV NODE_ENV="development"

# Clean yarn cache
RUN yarn cache clean --force

# Install dependencies using --production flag
RUN yarn install 

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["yarn", "dev"]
