FROM node:16.17.0-bullseye-slim

WORKDIR /usr/src/app

COPY . .

ENV NODE_ENV="staging"

RUN yarn cache clean --force

RUN yarn install --production --frozen-lockfile --network-timeout 100000

RUN yarn build

CMD [ "yarn", "start" ]

