FROM node:16.17.0-bullseye-slim

WORKDIR /usr/src/app

COPY . .

RUN yarn cache clean --force

RUN yarn config delete proxy

RUN npm config rm proxy

RUN npm config rm https-proxy

# ENV NODE_ENV="staging"

# RUN yarn install --production --frozen-lockfile --network-timeout 100000
RUN yarn install --network-timeout 100000

RUN yarn build

CMD [ "yarn", "start" ]

