import { AWS_COGNITO_BUSINESS_CLIENT_ID, AWS_COGNITO_MARKETPLACE_CLIENT_ID } from '@constants';

type TClientID = typeof AWS_COGNITO_BUSINESS_CLIENT_ID | typeof AWS_COGNITO_MARKETPLACE_CLIENT_ID;

export { TClientID };
