name: '[DEVELOPMENT] Continuous Integration (CI)'

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn lint

  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Build the Docker image
        run: docker build . --file .docker/api/Dockerfile.build.dev --tag careplace-rest-api-build-${GITHUB_REF##*/}:$(date +%s)

  test:
    name: Test
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

  security:
    name: Security
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
