name: '[PRODUCTION] Continuous Integration (CI)'

on:
  push:
    branches: [feat-cd]

permissions:
  contents: write

jobs:
  release:
    name: Tag & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Configure git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "admin@careplace.pt"

      - name: Generate changelog and version
        run: npx standard-version

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch:  feat-cd

      - name: Get latest tag
        id: get_latest_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Get Changelog
        id: get_changelog
        run: |
          changelog_content=$(cat CHANGELOG.md)
          echo "::set-output name=changelog::$changelog_content"

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.get_latest_tag.outputs.tag }}
          name: Release ${{ steps.get_latest_tag.outputs.tag }}
          bodyFile: CHANGELOG.md
          draft: true
          prerelease: true

     
