name: "[STAGING] Continuous Integration (CI)"

on:
  pull_request:
    branches: [ release/* ]
  push:
    branches: [ release/* ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Branch name
        run: echo running on branch '${GITHUB_REF##*/}'
      - name: Build the Docker image
        run: docker build . --file .docker/api/Dockerfile.stag --tag careplace-rest-api-build-${GITHUB_REF##*/}:$(date +%s)
