name: Docker Image CI

on:
  push:
    branches: [ "Master", "staging", "develop" ]
  pull_request:
    branches: [ "Master", "staging", "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag careplace-backend-build-${{ steps.extract_branch.outputs.branch }}:$(date +%s)
